baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"
theme = "LoveIt"
title = "Duncan's Blog"
[author]
email = "duncnacytseng@gmail.com"
link = ""
name = "DuncanTseng"
[languages.en.params.home.profile]
avatarURL = "images/photo2.jpg"
enable = true
gravatarEmail = ""
social = true
subtitle = "Full Stack developer"
title = "Duncan's Blog"
typeit = true
url = "posts/about/"
[languages.en.params.search]
absoluteURL = false
contentLength = 4000
enable = true
highlightTag = "em"
maxResultLength = 10
placeholder = ""
snippetLength = 30
type = "algolia"
[languages.en.params.search.algolia]
appID = "PASDMWALPK"
index = "index.en"
searchKey = "b42948e51daaa93df92381c8e2ac0f93"
[languages.en.params.social]
Email = "duncnacytseng@gmail.com"
[markup.highlight]
noClasses = false
[[menu.main]]
name = "關於我"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "tags"
name = "標籤"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "posts"
name = "Posts"
post = ""
pre = ""
title = ""
url = "/posts/"
weight = 1
[params]
version = "0.2.X"
[params.footer]
author = true
copyright = true
custom = ""
enable = true
hugo = true
license = "<a rel=\"license external nofollow noopener noreffer\" href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\">CC BY-NC 4.0</a>"
since = 2021
[params.page.comment]
enable = true
[params.page.comment.gitalk]
clientId = ""
clientSecret = ""
enable = true
owner = "Duncan8805"
repo = "Hugo"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
